### Get Clickup ticket info
# @no-cookie-jar
GET {{host}}/api/v2/task/{{ticket}}?team_id={{clickup_team_id}}&custom_task_ids=true
Authorization: {{clickup_token}}
User-Agent: vendic-clickup-change-status
Accept: {{accept}}